### ISSUE TITLE
[ Role cmd ] Add flag to list available roles

### ISSUE THREAD

**Issue by ashiishme** [askbuddie/askbuddie-bot#12]
**Is your feature request related to a problem? Please describe.**

No, this feature request is not associated with any problems.

**Describe the solution you'd like**

List out all the available roles for normal users that can be used with `role` command. This is not a separate command but a flag for our `role` command that is already available.

**Example:**
```
ab role --list
```

Above should display all the roles for normal users.

**Describe alternatives you've considered**

There are no alternatives, feel free to discuss below.

**Comment by rojen11** [comment]
Hi, I want to work on this.

**Comment by ashiishme** [comment]
@rojen11  Thank you so much. Assigned.
