### ISSUE TITLE
Empty `.env.example` file?

### ISSUE THREAD

**Issue by shreemaan-abhishek** [askbuddie/askbuddie-bot#39]
[This](https://github.com/askbuddie/askbuddie-bot/blame/main/README.md#L48) line on `README.md` says 

> look at the `.env.example` file for reference.

But [the file](https://github.com/askbuddie/askbuddie-bot/blob/main/.env.example) is empty.

**Comment by ashiishme** [comment]
Thanks for flagging this issue. For now if you are setting up the project locally please use:

```env
DISCORD_TOKEN=
```

In your `.env` file. I will leave this issue open for someone willing to get started with open-source.

**Comment by shreemaan-abhishek** [comment]
Heck yeah! Count me in!
