### ISSUE TITLE
Self Assign Roles

### ISSUE THREAD

**Issue by ashiishme** [askbuddie/askbuddie-bot#6]
**Is your feature request related to a problem? Please describe.**
No, it is not related to any problem.

**Describe the solution you'd like**

Due to the emoji limitation, we need an flag/option support in our bot that can help users to self assign them with multiple user roles.

##### Command Example:

```
ab role javascript
```

The above command should assign users with role `javascript`.

##### Advance Feature:

( Optional ) Allow users to assign multiple roles at once.

**Example:**

```
ab role --multi javascript typescript python
```

The above command should assign 3 roles to the user who executes the command.

**Describe alternatives you've considered**
There are no alternatives currently.

**Comment by rojen11** [comment]
I would like to work on this. and do we hardcore roles?

**Comment by ashiishme** [comment]
@rojen11  We don't have to hard-code list anywhere in the bot, when user pass the role through command, just check if the role exists and assign them to users.

**Comment by rojen11** [comment]
okay i think i understand.
